** -*- koshu -*-

|-- DIR  /code 192  /comment 108  /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- DIR  /code 127  /comment 91   /dir "calculator/Koshucode/Baala/Toolkit/Main"

|-- DIR-TOTAL  /code 319  /comment 199

|-- FILE  /code 48   /comment 49   /file "Element.hs"     /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 41   /comment 16   /file "Exit.hs"        /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 93   /comment 35   /file "Run.hs"         /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 10   /comment 8    /file "Version.hs"     /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 127  /comment 91   /file "KoshuMain.hs"   /dir "calculator/Koshucode/Baala/Toolkit/Main"

|-- FILE-TOTAL  /code 319  /comment 199
