** -*- koshu -*-

|-- DIR  /code 186  /comment 109  /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- DIR  /code 96   /comment 108  /dir "calculator/Koshucode/Baala/Toolkit/Main"

|-- DIR-TOTAL  /code 282  /comment 217

|-- FILE  /code 50   /comment 49   /file "Element.hs"     /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 41   /comment 16   /file "Exit.hs"        /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 85   /comment 36   /file "Run.hs"         /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 10   /comment 8    /file "Version.hs"     /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 96   /comment 108  /file "KoshuMain.hs"   /dir "calculator/Koshucode/Baala/Toolkit/Main"

|-- FILE-TOTAL  /code 282  /comment 217
