** -*- koshu -*-

|-- DIR  /code 193  /comment 109  /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- DIR  /code 130  /comment 91   /dir "calculator/Koshucode/Baala/Toolkit/Main"

|-- DIR-TOTAL  /code 323  /comment 200

|-- FILE  /code 48   /comment 49   /file "Element.hs"     /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 41   /comment 16   /file "Exit.hs"        /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 94   /comment 36   /file "Run.hs"         /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 10   /comment 8    /file "Version.hs"     /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 130  /comment 91   /file "KoshuMain.hs"   /dir "calculator/Koshucode/Baala/Toolkit/Main"

|-- FILE-TOTAL  /code 323  /comment 200
