-*- koshu -*-

about /package 'overture

|-- DIR  /code 24   /comment 32   /dir "overture/Koshucode/Baala/Overture"
|-- DIR  /code 25   /comment 28   /dir "overture/Koshucode/Baala/Overture/Name"

|-- DIR-TOTAL  /code 49  /comment 60

|-- FILE  /code 24   /comment 32   /file "Fn.hs"          /dir "overture/Koshucode/Baala/Overture"
|-- FILE  /code 10   /comment 9    /file "IntString.hs"   /dir "overture/Koshucode/Baala/Overture/Name"
|-- FILE  /code 7    /comment 9    /file "String.hs"      /dir "overture/Koshucode/Baala/Overture/Name"
|-- FILE  /code 8    /comment 10   /file "Text.hs"        /dir "overture/Koshucode/Baala/Overture/Name"

|-- FILE-TOTAL  /code 49  /comment 60
