-*- koshu -*-

about /package 'overture

|-- DIR  /code 6    /comment 5    /dir "overture/Koshucode/Baala"
|-- DIR  /code 46   /comment 54   /dir "overture/Koshucode/Baala/Overture"
|-- DIR  /code 25   /comment 28   /dir "overture/Koshucode/Baala/Overture/Name"
|-- DIR  /code 250  /comment 176  /dir "overture/Koshucode/Baala/Overture/Text"

|-- DIR-TOTAL  /code 327  /comment 263

|-- FILE  /code 6    /comment 5    /file "Overture.hs"    /dir "overture/Koshucode/Baala"
|-- FILE  /code 24   /comment 32   /file "Fn.hs"          /dir "overture/Koshucode/Baala/Overture"
|-- FILE  /code 10   /comment 9    /file "IntString.hs"   /dir "overture/Koshucode/Baala/Overture/Name"
|-- FILE  /code 7    /comment 9    /file "String.hs"      /dir "overture/Koshucode/Baala/Overture/Name"
|-- FILE  /code 8    /comment 10   /file "Text.hs"        /dir "overture/Koshucode/Baala/Overture/Name"
|-- FILE  /code 8    /comment 5    /file "Text.hs"        /dir "overture/Koshucode/Baala/Overture"
|-- FILE  /code 88   /comment 58   /file "Category.hs"    /dir "overture/Koshucode/Baala/Overture/Text"
|-- FILE  /code 103  /comment 40   /file "Unicode.hs"     /dir "overture/Koshucode/Baala/Overture/Text"
|-- FILE  /code 59   /comment 78   /file "Utility.hs"     /dir "overture/Koshucode/Baala/Overture/Text"
|-- FILE  /code 14   /comment 17   /file "Type.hs"        /dir "overture/Koshucode/Baala/Overture"

|-- FILE-TOTAL  /code 327  /comment 263
