-*- koshu -*-

about /package 'rop-flat

|-- DIR  /code 28   /comment 6    /dir "rop-flat/Koshucode/Baala/Rop"
|-- DIR  /code 1542  /comment 1171  /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- DIR  /code 211  /comment 202  /dir "rop-flat/Koshucode/Baala/Rop/Flat/Lattice"

|-- DIR-TOTAL  /code 1781  /comment 1379

|-- FILE  /code 28   /comment 6    /file "Flat.hs"        /dir "rop-flat/Koshucode/Baala/Rop"
|-- FILE  /code 84   /comment 53   /file "Check.hs"       /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 98   /comment 58   /file "Control.hs"     /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 174  /comment 109  /file "Elem.hs"        /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 189  /comment 100  /file "Gadget.hs"      /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 8    /comment 26   /file "Lattice.hs"     /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 100  /comment 72   /file "Restrict.hs"    /dir "rop-flat/Koshucode/Baala/Rop/Flat/Lattice"
|-- FILE  /code 19   /comment 20   /file "Rop.hs"         /dir "rop-flat/Koshucode/Baala/Rop/Flat/Lattice"
|-- FILE  /code 92   /comment 110  /file "Tropashko.hs"   /dir "rop-flat/Koshucode/Baala/Rop/Flat/Lattice"
|-- FILE  /code 66   /comment 40   /file "Message.hs"     /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 178  /comment 104  /file "Meta.hs"        /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 64   /comment 50   /file "Order.hs"       /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 106  /comment 71   /file "Peripheral.hs"  /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 56   /comment 45   /file "PoScale.hs"     /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 65   /comment 45   /file "Resource.hs"    /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 32   /comment 8    /file "Rops.hs"        /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 48   /comment 55   /file "Source.hs"      /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 198  /comment 234  /file "Subtext.hs"     /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 97   /comment 110  /file "Term.hs"        /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 79   /comment 63   /file "TermGadget.hs"  /dir "rop-flat/Koshucode/Baala/Rop/Flat"

|-- FILE-TOTAL  /code 1781  /comment 1379
