-*- koshu -*-

about /package 'rop-flat

|-- DIR  /code 38   /comment 12   /dir "rop-flat/Koshucode/Baala/Rop"
|-- DIR  /code 246  /comment 162  /dir "rop-flat/Koshucode/Baala/Rop/Base"
|-- DIR  /code 1198  /comment 722  /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- DIR  /code 183  /comment 174  /dir "rop-flat/Koshucode/Baala/Rop/Flat/Lattice"

|-- DIR-TOTAL  /code 1665  /comment 1070

|-- FILE  /code 10   /comment 6    /file "Base.hs"        /dir "rop-flat/Koshucode/Baala/Rop"
|-- FILE  /code 49   /comment 13   /file "Define.hs"      /dir "rop-flat/Koshucode/Baala/Rop/Base"
|-- FILE  /code 123  /comment 75   /file "Get.hs"         /dir "rop-flat/Koshucode/Baala/Rop/Base"
|-- FILE  /code 11   /comment 9    /file "Message.hs"     /dir "rop-flat/Koshucode/Baala/Rop/Base"
|-- FILE  /code 22   /comment 39   /file "Rop.hs"         /dir "rop-flat/Koshucode/Baala/Rop/Base"
|-- FILE  /code 41   /comment 26   /file "Term.hs"        /dir "rop-flat/Koshucode/Baala/Rop/Base"
|-- FILE  /code 28   /comment 6    /file "Flat.hs"        /dir "rop-flat/Koshucode/Baala/Rop"
|-- FILE  /code 28   /comment 5    /file "Bundle.hs"      /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 82   /comment 49   /file "Check.hs"       /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 94   /comment 48   /file "Control.hs"     /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 49   /comment 23   /file "DepRank.hs"     /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 177  /comment 100  /file "Gadget.hs"      /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 8    /comment 26   /file "Lattice.hs"     /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 93   /comment 53   /file "Restrict.hs"    /dir "rop-flat/Koshucode/Baala/Rop/Flat/Lattice"
|-- FILE  /code 18   /comment 21   /file "Rop.hs"         /dir "rop-flat/Koshucode/Baala/Rop/Flat/Lattice"
|-- FILE  /code 72   /comment 100  /file "Tropashko.hs"   /dir "rop-flat/Koshucode/Baala/Rop/Flat/Lattice"
|-- FILE  /code 59   /comment 35   /file "Message.hs"     /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 172  /comment 84   /file "Meta.hs"        /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 198  /comment 107  /file "Peripheral.hs"  /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 65   /comment 36   /file "Resource.hs"    /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 49   /comment 73   /file "Source.hs"      /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 141  /comment 83   /file "Term.hs"        /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 76   /comment 53   /file "TermGadget.hs"  /dir "rop-flat/Koshucode/Baala/Rop/Flat"

|-- FILE-TOTAL  /code 1665  /comment 1070
