-*- koshu -*-

about /package 'rop-flat

|-- DIR  /code 38   /comment 12   /dir "rop-flat/Koshucode/Baala/Rop"
|-- DIR  /code 230  /comment 184  /dir "rop-flat/Koshucode/Baala/Rop/Base"
|-- DIR  /code 1553  /comment 1173  /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- DIR  /code 215  /comment 203  /dir "rop-flat/Koshucode/Baala/Rop/Flat/Lattice"

|-- DIR-TOTAL  /code 2036  /comment 1572

|-- FILE  /code 10   /comment 6    /file "Base.hs"        /dir "rop-flat/Koshucode/Baala/Rop"
|-- FILE  /code 18   /comment 12   /file "Define.hs"      /dir "rop-flat/Koshucode/Baala/Rop/Base"
|-- FILE  /code 123  /comment 91   /file "Get.hs"         /dir "rop-flat/Koshucode/Baala/Rop/Base"
|-- FILE  /code 16   /comment 12   /file "Message.hs"     /dir "rop-flat/Koshucode/Baala/Rop/Base"
|-- FILE  /code 24   /comment 40   /file "Rop.hs"         /dir "rop-flat/Koshucode/Baala/Rop/Base"
|-- FILE  /code 49   /comment 29   /file "Term.hs"        /dir "rop-flat/Koshucode/Baala/Rop/Base"
|-- FILE  /code 28   /comment 6    /file "Flat.hs"        /dir "rop-flat/Koshucode/Baala/Rop"
|-- FILE  /code 32   /comment 5    /file "Bundle.hs"      /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 81   /comment 49   /file "Check.hs"       /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 100  /comment 55   /file "Control.hs"     /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 176  /comment 107  /file "Elem.hs"        /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 184  /comment 113  /file "Gadget.hs"      /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 8    /comment 26   /file "Lattice.hs"     /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 103  /comment 72   /file "Restrict.hs"    /dir "rop-flat/Koshucode/Baala/Rop/Flat/Lattice"
|-- FILE  /code 18   /comment 21   /file "Rop.hs"         /dir "rop-flat/Koshucode/Baala/Rop/Flat/Lattice"
|-- FILE  /code 94   /comment 110  /file "Tropashko.hs"   /dir "rop-flat/Koshucode/Baala/Rop/Flat/Lattice"
|-- FILE  /code 67   /comment 40   /file "Message.hs"     /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 173  /comment 97   /file "Meta.hs"        /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 63   /comment 39   /file "Order.hs"       /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 109  /comment 72   /file "Peripheral.hs"  /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 57   /comment 35   /file "PoScale.hs"     /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 66   /comment 42   /file "Resource.hs"    /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 50   /comment 77   /file "Source.hs"      /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 208  /comment 237  /file "Subtext.hs"     /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 102  /comment 118  /file "Term.hs"        /dir "rop-flat/Koshucode/Baala/Rop/Flat"
|-- FILE  /code 77   /comment 61   /file "TermGadget.hs"  /dir "rop-flat/Koshucode/Baala/Rop/Flat"

|-- FILE-TOTAL  /code 2036  /comment 1572
