-*- koshu -*-

about /package 'toolkit

|-- DIR  /code 128  /comment 75   /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- DIR  /code 354  /comment 146  /dir "toolkit/Koshucode/Baala/Toolkit/Main"

|-- DIR-TOTAL  /code 482  /comment 221

|-- FILE  /code 68   /comment 46   /file "Change.hs"      /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 27   /comment 12   /file "Input.hs"       /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 33   /comment 17   /file "RDF.hs"         /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 74   /comment 38   /file "KoshuChange.hs"  /dir "toolkit/Koshucode/Baala/Toolkit/Main"
|-- FILE  /code 109  /comment 44   /file "KoshuRdf.hs"    /dir "toolkit/Koshucode/Baala/Toolkit/Main"
|-- FILE  /code 171  /comment 64   /file "KoshuSyntax.hs"  /dir "toolkit/Koshucode/Baala/Toolkit/Main"

|-- FILE-TOTAL  /code 482  /comment 221
