-*- koshu -*-

about /package 'toolkit

|-- DIR  /code 129  /comment 82   /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- DIR  /code 360  /comment 147  /dir "toolkit/Koshucode/Baala/Toolkit/Main"

|-- DIR-TOTAL  /code 489  /comment 229

|-- FILE  /code 70   /comment 49   /file "Change.hs"      /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 26   /comment 16   /file "Input.hs"       /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 33   /comment 17   /file "RDF.hs"         /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 74   /comment 38   /file "KoshuChange.hs"  /dir "toolkit/Koshucode/Baala/Toolkit/Main"
|-- FILE  /code 112  /comment 45   /file "KoshuRdf.hs"    /dir "toolkit/Koshucode/Baala/Toolkit/Main"
|-- FILE  /code 174  /comment 64   /file "KoshuSyntax.hs"  /dir "toolkit/Koshucode/Baala/Toolkit/Main"

|-- FILE-TOTAL  /code 489  /comment 229
