# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-11.10

# User packages to be built.
packages:
- base
- calculator
- cop
- core
- data
- data-plus
- overture
- rop
- rop-cox
- rop-flat
- rop-nested
- subtext
- syntax
- toolkit
- type
- writer

# Dependency packages to be pulled from upstream that are not in the resolver
# using the same syntax as the packages field.
extra-deps:
- hgal-2.0.0.2
- rdf4h-2.0.0
