-*- koshu -*-

about /package 'calculator

|-- DIR  /code 123  /comment 79   /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- DIR  /code 238  /comment 55   /dir "calculator/Koshucode/Baala/Toolkit/Main"

|-- DIR-TOTAL  /code 361  /comment 134

|-- FILE  /code 66   /comment 46   /file "Element.hs"     /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 22   /comment 10   /file "Global.hs"      /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 25   /comment 12   /file "Run.hs"         /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 10   /comment 11   /file "Version.hs"     /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 71   /comment 15   /file "KoshuFilter.hs"  /dir "calculator/Koshucode/Baala/Toolkit/Main"
|-- FILE  /code 167  /comment 40   /file "KoshuMain.hs"   /dir "calculator/Koshucode/Baala/Toolkit/Main"

|-- FILE-TOTAL  /code 361  /comment 134
