-*- koshu -*-

about /package 'calculator

|-- DIR  /code 122  /comment 78   /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- DIR  /code 220  /comment 126  /dir "calculator/Koshucode/Baala/Toolkit/Main"

|-- DIR-TOTAL  /code 342  /comment 204

|-- FILE  /code 65   /comment 45   /file "Element.hs"     /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 22   /comment 10   /file "Global.hs"      /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 25   /comment 12   /file "Run.hs"         /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 10   /comment 11   /file "Version.hs"     /dir "calculator/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 69   /comment 15   /file "KoshuFilter.hs"  /dir "calculator/Koshucode/Baala/Toolkit/Main"
|-- FILE  /code 151  /comment 111  /file "KoshuMain.hs"   /dir "calculator/Koshucode/Baala/Toolkit/Main"

|-- FILE-TOTAL  /code 342  /comment 204
