** -*- koshu -*-
**  
**  INPUT
**    DATA.k
**    negation.k
**    

|-- S  /negation #false  /criteria #true  /sno 'S1  /city 'London
|-- S  /negation #true  /criteria #false  /sno 'S2  /city 'Paris
|-- S  /negation #true  /criteria #false  /sno 'S3  /city 'Paris
|-- S  /negation #false  /criteria #true  /sno 'S4  /city 'London
|-- S  /negation #true  /criteria #false  /sno 'S5  /city 'Athens
**  (5 judges)

