** -*- koshu -*-
**  
**  INPUT
**    DATA.k
**    renaming.k
**    

|-- P2  /pno P1  /pname Nut  /col Red  /wt 12  /city London
|-- P2  /pno P2  /pname Bolt  /col Green  /wt 17  /city Paris
|-- P2  /pno P3  /pname Screw  /col Blue  /wt 17  /city Oslo
|-- P2  /pno P4  /pname Screw  /col Red  /wt 14  /city London
|-- P2  /pno P5  /pname Cam  /col Blue  /wt 12  /city Paris

|-- P2  /pno P6  /pname Cog  /col Red  /wt 19  /city London
**  (6 judges)

