** -*- koshu -*-
**  
**  INPUT
**    DATA.k
**    repeating-group.k
**    

|-- P  /pname 'Nut  /qty-list [300 300]  /qty-total 600  /pno 'P1
|-- P  /pname 'Bolt  /qty-list [200 200 400 200]  /qty-total 1000  /pno 'P2
|-- P  /pname 'Screw  /qty-list [400]  /qty-total 400  /pno 'P3
|-- P  /pname 'Screw  /qty-list [300 200]  /qty-total 500  /pno 'P4
|-- P  /pname 'Cam  /qty-list [400 100]  /qty-total 500  /pno 'P5

|-- P  /pname 'Cog  /qty-list [100]  /qty-total 100  /pno 'P6
**  (6 judges)

