** -*- koshu -*-

|-- DIR  /code 127  /comment 75   /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- DIR  /code 353  /comment 147  /dir "toolkit/Koshucode/Baala/Toolkit/Main"

|-- DIR-TOTAL  /code 480  /comment 222

|-- FILE  /code 67   /comment 46   /file "Change.hs"      /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 27   /comment 12   /file "Input.hs"       /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 33   /comment 17   /file "RDF.hs"         /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 73   /comment 38   /file "KoshuChange.hs"  /dir "toolkit/Koshucode/Baala/Toolkit/Main"
|-- FILE  /code 109  /comment 44   /file "KoshuRdf.hs"    /dir "toolkit/Koshucode/Baala/Toolkit/Main"
|-- FILE  /code 171  /comment 65   /file "KoshuSyntax.hs"  /dir "toolkit/Koshucode/Baala/Toolkit/Main"

|-- FILE-TOTAL  /code 480  /comment 222
