** -*- koshu -*-

|-- DIR  /code 137  /comment 72   /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- DIR  /code 500  /comment 215  /dir "toolkit/Koshucode/Baala/Toolkit/Main"

|-- DIR-TOTAL  /code 637  /comment 287

|-- FILE  /code 77   /comment 40   /file "Change.hs"      /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 27   /comment 15   /file "Input.hs"       /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 33   /comment 17   /file "RDF.hs"         /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 73   /comment 43   /file "KoshuChange.hs"  /dir "toolkit/Koshucode/Baala/Toolkit/Main"
|-- FILE  /code 112  /comment 44   /file "KoshuRdf.hs"    /dir "toolkit/Koshucode/Baala/Toolkit/Main"
|-- FILE  /code 201  /comment 78   /file "KoshuRegress.hs"  /dir "toolkit/Koshucode/Baala/Toolkit/Main"
|-- FILE  /code 114  /comment 50   /file "KoshuSyntax.hs"  /dir "toolkit/Koshucode/Baala/Toolkit/Main"

|-- FILE-TOTAL  /code 637  /comment 287
