** -*- koshu -*-

|-- DIR  /code 127  /comment 78   /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- DIR  /code 296  /comment 142  /dir "toolkit/Koshucode/Baala/Toolkit/Main"

|-- DIR-TOTAL  /code 423  /comment 220

|-- FILE  /code 67   /comment 46   /file "Change.hs"      /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 27   /comment 15   /file "Input.hs"       /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 33   /comment 17   /file "RDF.hs"         /dir "toolkit/Koshucode/Baala/Toolkit/Library"
|-- FILE  /code 73   /comment 38   /file "KoshuChange.hs"  /dir "toolkit/Koshucode/Baala/Toolkit/Main"
|-- FILE  /code 109  /comment 44   /file "KoshuRdf.hs"    /dir "toolkit/Koshucode/Baala/Toolkit/Main"
|-- FILE  /code 114  /comment 60   /file "KoshuSyntax.hs"  /dir "toolkit/Koshucode/Baala/Toolkit/Main"

|-- FILE-TOTAL  /code 423  /comment 220
